module transport

import sync

// listen-only — the wires the operator marked "never transmit", and the ONE place that is
// enforced.
//
// WHY NOT AT EACH EMITTER. Quick Send, the generators, the simulated ECUs, replay, diagnostics,
// the shell, the Lua runner and the restbus tool all put frames on a wire, and each opens its
// own bus to do it. A rule checked at every emitter holds until somebody adds the ninth: issue
// #117 found it checked in exactly one of them (replay) while the checkbox's tooltip promised
// all of them. Checked inside `open`, an emitter cannot opt out, because it never sees the
// decision -- it is simply handed a bus that refuses.
//
// WHY NOT IN THE ADDRESS. `,silent` already reaches the Vector transceiver through the interface
// string, so spelling it that way for every backend looks like the smaller change. It is not.
// destination_key and wire_key_for reduce an address to a WIRE IDENTITY, and they strip a mode
// suffix only for `vector:` -- so `pcan:PCAN_USBBUS1,silent` and `pcan:PCAN_USBBUS1` would key
// as two different wires, and the refcounted single-open that issue #147 exists for would open
// one channel twice and lose a reader. Listen-only is a policy ON a wire, not part of its name,
// and this table is what keeps it out of the name.
//
// Process-wide, like sim's fault table and for the same reason: the GUI, a script and a CLI tool
// must not be able to disagree about whether a bus is allowed to transmit.
//
// WHY REFUSING TO SEND IS ONLY HALF OF IT. `SilentBus` stops US from putting a frame on the wire,
// and for the software buses that is the whole of listening-only. On real CAN it is not: an
// ACKNOWLEDGEMENT is generated by the CONTROLLER, in hardware, on every frame it accepts, and no
// amount of not calling send suppresses it. On a bus with one other node our ACK is the difference
// between that node's frames succeeding and it going error-passive -- so a tester marked
// listen-only was still changing the thing it came to observe, while the checkbox said otherwise.
// A backend that can silence its transceiver must therefore do BOTH, and each of them
// (`vector:...,silent`, `canSetBusOutputControl`, `PCAN_LISTEN_ONLY`) reads this table rather than
// keeping its own answer. A backend that CANNOT -- the software buses, SocketCAN's `vcan` -- has
// no ACK to suppress, so software refusal is complete there by construction.
//
// Each of those backends re-asks PER RECEIVE rather than caching the answer at open, for exactly
// the reason the send path does: a row can be toggled mid-run and a project replaced, so an answer
// frozen at open time goes stale on a wire that is still up. A receive loop runs continuously on a
// monitored wire, so the reconcile costs one lookup in the common case and reaches the controller
// within one poll of the operator clicking.

// WirePolicy is everything a project declares ABOUT a wire rather than about a frame: whether it
// may transmit, and what format the frames it originates take.
//
// ONE ENTRY, ONE LOCK, ONE SWAP, because the two are published together and read together. Held in
// separate tables they were two swaps, and a bus a script still holds could send in the gap — with
// the new silence state and the previous project's format, which is the stale policy the per-send
// lookup exists to prevent (codex #202 r2).
pub struct WirePolicy {
pub:
	silent  bool
	framing Framing
}

pub struct ListenTable {
mut:
	mu    sync.Mutex
	wires map[string]WirePolicy
}

// listen_tbl is THE listen-only table for the process. A global for the reason sim.injected is
// one: the side that decides (a project being applied) and the side that enforces (every open,
// down every call chain there is) would otherwise need a pointer threaded between them.
__global listen_tbl = &ListenTable{}

// wire_key names the WIRE this address reaches, with the bitrate removed -- one physical bus,
// however many rows point at it and whatever rate each asks for.
//
// NOT wire_key_for, and the difference is load-bearing. That one takes the project's `adapter`
// field, so code READING a foreign project can resolve a vendor name the local platform would
// not recognise, and it cuts at `@` unconditionally. Here the address is one we are about to
// open on THIS machine, and `@` is a bitrate suffix only on a vendor address: `inproc:bench@A`
// is a bus NAME, and cutting it there names a different hub than the one the operator marked.
pub fn wire_key(iface string) string {
	if vendor_iface(iface.trim_space()) {
		return vendor_destination_key(iface).all_before('@')
	}
	// UNTRIMMED on this path, deliberately. canonical_iface does not trim either, and says why:
	// the dispatcher does not, so `inproc:bench` and `inproc:bench ` are two separate hubs.
	// Trimming here would let one tick silence a bus nobody ticked.
	return canonical_iface(iface)
}

// set_listen_only marks (or unmarks) a wire. Called where a project is APPLIED, once per
// channel, rather than where a frame is sent.
pub fn set_listen_only(iface string, on bool) {
	k := wire_key(iface)
	listen_tbl.mu.lock()
	mut p := listen_tbl.wires[k] or { WirePolicy{} }
	p = WirePolicy{
		...p
		silent: on
	}
	if p.silent || p.framing.fd {
		listen_tbl.wires[k] = p
	} else {
		// An entry saying nothing is no entry. Keeping one would be a second way to spell the
		// default, which is how two spellings of one state come to disagree.
		listen_tbl.wires.delete(k)
	}
	listen_tbl.mu.unlock()
}

// wire_policy is everything declared about this wire; the zero value where nothing was.
pub fn wire_policy(iface string) WirePolicy {
	k := wire_key(iface)
	listen_tbl.mu.lock()
	v := listen_tbl.wires[k] or { WirePolicy{} }
	listen_tbl.mu.unlock()
	return v
}

// replace_wire_policy swaps the WHOLE set — silence and format together — under one lock.
//
// The atomic publish the two-table version could not give. `silent` and `framed` are keyed the same
// way, so a wire may appear in either, both or neither.
pub fn replace_wire_policy(silent []string, framed map[string]Framing) {
	mut next := map[string]WirePolicy{}
	for i in silent {
		k := wire_key(i)
		next[k] = WirePolicy{
			...(next[k] or { WirePolicy{} })
			silent: true
		}
	}
	for i, fr in framed {
		if !fr.fd {
			continue
		}
		k := wire_key(i)
		next[k] = WirePolicy{
			...(next[k] or { WirePolicy{} })
			framing: fr
		}
	}
	listen_tbl.mu.lock()
	listen_tbl.wires = next.move()
	listen_tbl.mu.unlock()
}

// set_wire_framing marks one wire. Keyed like listen-only, so `vector:1` and `vector:ch1` are one
// wire here exactly as they are there — two spellings of one transceiver cannot carry two formats.
pub fn set_wire_framing(iface string, fr Framing) {
	k := wire_key(iface)
	listen_tbl.mu.lock()
	mut p := listen_tbl.wires[k] or { WirePolicy{} }
	p = WirePolicy{
		...p
		framing: fr
	}
	if p.silent || p.framing.fd {
		listen_tbl.wires[k] = p
	} else {
		listen_tbl.wires.delete(k)
	}
	listen_tbl.mu.unlock()
}

// clear_wire_framing drops every format mark, leaving silence marks alone.
pub fn clear_wire_framing() {
	listen_tbl.mu.lock()
	mut next := map[string]WirePolicy{}
	for k, p in listen_tbl.wires {
		if p.silent {
			next[k] = WirePolicy{
				silent: true
			}
		}
	}
	listen_tbl.wires = next.move()
	listen_tbl.mu.unlock()
}

// is_listen_only reports whether this wire refuses transmission.
pub fn is_listen_only(iface string) bool {
	return wire_policy(iface).silent
}

// replace_listen_only swaps the WHOLE set under one lock.
//
// Not clear-then-set. Those are two locked operations with a gap between them, and a bus opened
// in that gap -- by a script worker, the shell, a replay spawn, anything holding no lock of its
// own -- reads an empty table and gets a transmitting bus for its whole lifetime. The window is
// microseconds and the consequence is a wire the operator ticked silent transmitting until Stop,
// which is the failure this whole change exists to remove.
pub fn replace_listen_only(ifaces []string) {
	replace_wire_policy(ifaces, map[string]Framing{})
}

// clear_listen_only drops every mark. Used when a project is replaced -- a wire marked by the
// old one must not silence a new project that happens to reuse the interface, which is the same
// hazard sim.clear_all() exists for and the same answer.
pub fn clear_listen_only() {
	listen_tbl.mu.lock()
	listen_tbl.wires.clear()
	listen_tbl.mu.unlock()
}

// SilentBus is a bus that hears everything and says nothing.
//
// It REFUSES rather than silently dropping. A send that vanishes without a word is
// indistinguishable from a bus that is broken, and this repo has already paid for that once --
// #141 exists because a channel that failed to open said nothing. The error travels the path a
// refusal already travels: the trace marks the row NOT SENT, which is a state its legend
// already explains.
struct SilentBus {
mut:
	inner Bus
	iface string
	// Whether this bus ORIGINATES frames. False for a bus whose caller has already decided the
	// format — see open_verbatim.
	verbatim bool
}

fn (mut s SilentBus) send(frame CanFrame) ! {
	// ASKED NOW, not at open. See silenced() below for why the answer is not cached.
	//
	// ONE READ FOR BOTH ANSWERS. Silence and format are published together precisely so a send
	// cannot straddle two policy versions, and reading the entry twice threw that away: a wire
	// marked listen-only between the two reads still transmitted, which is the one guarantee the
	// checkbox makes (codex #202 r3).
	// THE CONTROLLER FIRST, BEFORE THIS DECIDES. Refusing the send is the software half; the ACK
	// is the transceiver's, and on a wire whose only handles are transmit taps — a disabled row
	// keeps them open on purpose (#165) — this refusal is the ONLY thing that ever runs. Reconciled
	// after the refusal, or inside the backend's own send, the mark going ON could never reach the
	// driver at all: the process would stop transmitting while the controller went on acknowledging
	// the bus indefinitely (codex round 1 on #219).
	//
	// A backend with no controller answers by doing nothing, so this costs one call through the
	// wrappers on every other bus in the app.
	s.inner.reconcile_silence()!
	p := wire_policy(s.iface)
	if p.silent {
		return error('${s.iface}: listen-only — nothing is transmitted on this wire')
	}
	// AND THE FORMAT THIS WIRE CARRIES, for the same reason silence is applied here: every emitter
	// opens its own bus, and a rule checked at each of them holds until somebody adds the next one.
	// Frames this app CONSTRUCTS are built classic, so without this a channel configured as CAN-FD
	// could be exercised by nothing but replay (#185, framing.v).
	//
	// NOT ON A VERBATIM BUS, whose caller has already decided — the GUI's tap frames before it
	// records, and replay reproduces a recording rather than originating anything.
	if s.verbatim {
		s.inner.send(frame)!
		return
	}
	s.inner.send(p.framing.apply(frame))!
}

fn (mut s SilentBus) recv(timeout_ms int) !CanFrame {
	return s.inner.recv(timeout_ms)!
}

fn (mut s SilentBus) reconcile_silence() ! {
	s.inner.reconcile_silence()!
}

fn (mut s SilentBus) close() {
	s.inner.close()
}

fn (mut s SilentBus) health() BusHealth {
	return s.inner.health()
}

// silenced wraps every bus `open` hands out. ALWAYS, and the decision is deferred to the send.
//
// It used to wrap only wires marked at open time, which reads as the cheaper thing and is a
// different promise: it freezes the policy into the handle. Everything that changes the marks
// afterwards then cannot reach a bus that is already open -- enabling a listen-only row mid-run
// gives its fresh taps a writable bus, disabling one leaves the running taps refusing, and a Lua
// script (explicitly allowed to outlive Stop, holding its bus across a project edit) keeps
// transmitting on a wire the operator has since ticked silent. All three are the same bug
// (codex #164 r1, two P1s), and asking per send is the only version with no stale copy in it.
//
// The cost is one map read behind an uncontended mutex per frame. The replay dispatcher already
// takes an app-wide lock per frame for a comparable reason and records the arithmetic: tens of
// nanoseconds against a send, on a path already doing a syscall.
fn silenced(iface string, b Bus) Bus {
	return &SilentBus{
		inner: b
		iface: iface
	}
}

// verbatim marks a bus whose caller owns the frame's FORMAT, so `open` does not originate-frame it.
//
// TWO CALLERS, ONE REASON: the frame reaching this bus is already the frame that should go on the
// wire, and a second decision here could only disagree with the first.
//
//   - REPLAY reproduces a recording. Its classic frames are classic because they were RECORDED
//     that way, and `fd == false` cannot distinguish that from an emitter that simply did not say
//     — so on an FD wire replay's classic traffic was being promoted, silently rewriting the
//     recording it exists to reproduce (codex #202 r3).
//   - THE GUI'S TAP frames before it normalises and RECORDS, because wiretap's identity includes
//     fd/brs. Framing again underneath could observe a different policy version mid-send and put a
//     frame on the wire that does not match the one in the trace.
//
// Everything else — the ISO-TP servers, flash, Lua, the headless UDS nodes, the simulated ECUs —
// holds an ordinary bus and is framed here, which is the whole point of #185.
pub fn verbatim(mut b Bus) Bus {
	if mut b is SilentBus {
		b.verbatim = true
	}
	return b
}
