// silentcheck — prove that a wire marked listen-only stops ACKNOWLEDGING, not just transmitting.
//
// WHY THIS NEEDS A BENCH AND A SECOND NODE. Listen-only has two halves. The software half is
// `SilentBus` refusing to send, and a unit test can check it on an `inproc:` bus in microseconds.
// The hardware half cannot be checked that way at all: an ACK is generated by the CONTROLLER, on
// every frame it accepts, and the only observer of its absence is ANOTHER NODE — which sees its
// own frames fail and its error counters climb. So the measurement is necessarily two adapters and
// a cable, and the thing measured is the health of the node that is NOT under test.
//
// VENDOR-AGNOSTIC ON PURPOSE. It takes two interface strings rather than channel numbers, so the
// same run proves Kvaser against Kvaser, PCAN against PCAN, or one vendor against the other — and
// the cross-vendor pairing is the more convincing one, because neither driver is scoring its own
// homework.
//
//   v -enable-globals -path "@vlib|@vmodules|modules" run cmd/silentcheck/main.v \
//       --listener kvaser:0@500000 --talker kvaser:1@500000
//   v -enable-globals -path "@vlib|@vmodules|modules" run cmd/silentcheck/main.v \
//       --listener pcan:PCAN_USBBUS1@500000 --talker kvaser:2@500000
//
// IT TRANSMITS, from `--talker`, deliberately and repeatedly. Do not point it at a bus you are not
// willing to disturb — and note that the point of phase 2 is to drive the talker's controller into
// its fault ladder, which is a state a real ECU would report.
//
// `-enable-globals` is not optional: modules/transport/inproc.v uses `__global`.
module main

import os
import time
import transport

struct Opts {
mut:
	listener string
	talker   string
	frames   int = 6
	timeout  int = 300
	id       u32 = 0x321
	// HOW MANY HANDLES THE LISTENER WIRE HOLDS, defaulting to what a GUI Start actually opens: a
	// monitor plus transmit taps. See the `--handles` note in usage() for why this is not 1.
	handles int = 3
}

fn usage() {
	println('silentcheck — prove a listen-only wire stops acknowledging')
	println('')
	println('  --listener <iface>    the wire under test; it is marked listen-only and never sends')
	println('  --talker <iface>      the second node, on the same bus; it TRANSMITS')
	println('  --handles <n>         handles to hold open on the listener wire (default 3)')
	println('                        A GUI Start opens each wire several times — a monitor plus')
	println('                        transmit taps — and on Kvaser the channel mode CANNOT be')
	println('                        changed through one handle while its siblings are on the bus:')
	println('                        the driver accepts the call and ignores it. A one-handle bench')
	println('                        therefore passes while the real configuration silently fails,')
	println('                        which is exactly what happened. 1 to test a single handle.')
	println('  --frames <n>          frames per phase (default 6)')
	println('  --timeout <ms>        receive timeout per frame (default 300)')
	println('  --id <hex|dec>        CAN id to send (default 0x321)')
	println('')
	println('Both wires must be on one terminated bus, and they must be different wires:')
	println('a channel cannot fail to acknowledge its own transmission.')
}

fn main() {
	mut o := Opts{}
	args := os.args[1..]
	for i := 0; i < args.len; i++ {
		match args[i] {
			'--listener' {
				i++
				o.listener = arg_str(args, i, '--listener')
			}
			'--talker' {
				i++
				o.talker = arg_str(args, i, '--talker')
			}
			'--frames' {
				i++
				o.frames = arg_int(args, i, '--frames')
			}
			'--handles' {
				i++
				o.handles = arg_int(args, i, '--handles')
			}
			'--timeout' {
				i++
				o.timeout = arg_int(args, i, '--timeout')
			}
			'--id' {
				i++
				o.id = u32(arg_int(args, i, '--id'))
			}
			'--help', '-h' {
				usage()
				return
			}
			else {
				eprintln('unknown argument: ${args[i]}')
				usage()
				exit(2)
			}
		}
	}
	if o.listener == '' || o.talker == '' {
		eprintln('both --listener and --talker are required')
		usage()
		exit(2)
	}
	// THE SAME WIRE WOULD REPORT A PASS FOR THE WRONG REASON. A controller does not acknowledge
	// its own frame in the first place, so pointing both at one channel measures nothing and
	// looks like success. Compared as WIRES, so `kvaser:0@500000` and `kvaser:0` are caught.
	if transport.wire_key(o.listener) == transport.wire_key(o.talker) {
		eprintln('--listener and --talker name the same wire (${transport.wire_key(o.listener)}) — a')
		eprintln('channel never acknowledges its own transmission, so this would pass without proving anything.')
		exit(2)
	}
	if o.frames < 1 {
		eprintln('--frames must be at least 1')
		exit(2)
	}
	if o.handles < 1 {
		eprintln('--handles must be at least 1')
		exit(2)
	}
	// POSITIVE, AND THE LOWER BOUND IS NOT PEDANTRY. The Bus contract reads a NEGATIVE timeout as
	// "block forever", and `settle` receives before any traffic is sent — so `--timeout -1` did not
	// produce a wrong answer, it produced no answer at all: the tool sat in recv on a quiet bus
	// until somebody noticed (codex round 2 on #219). Zero is refused for the neighbouring reason,
	// that it makes every phase report nothing heard and phase 1 then fails the whole run for a
	// bench that is fine.
	if o.timeout < 1 {
		eprintln('--timeout must be positive (milliseconds): a negative one means "block forever" to a bus,')
		eprintln('and this tool receives before it transmits, so ${o.timeout} would hang rather than report.')
		exit(2)
	}
	exit(run(o))
}

fn run(o Opts) int {
	// CLEARED FIRST, because the table is process-wide and a stale mark from anything else in
	// this process would make phase 1's baseline a second copy of phase 2.
	transport.clear_listen_only()

	mut listener := transport.open(o.listener) or {
		eprintln('could not open listener ${o.listener}: ${err}')
		return 1
	}
	defer {
		listener.close()
	}
	// SIBLING HANDLES ON THE SAME WIRE, held open and otherwise unused, because a wire in this app
	// is normally held by several: a monitor plus named and anonymous transmit taps. They are not
	// decoration — on Kvaser the channel's output mode cannot be changed through one handle while
	// its siblings are on the bus, and the driver reports success anyway. A bench that opened the
	// listener once passed every phase while the configuration the GUI actually uses went on
	// acknowledging (codex round 5 on #219).
	mut siblings := []transport.Bus{}
	for n in 1 .. o.handles {
		sib := transport.open(o.listener) or {
			eprintln('could not open listener handle ${n + 1} of ${o.handles} on ${o.listener}: ${err}')
			return 1
		}
		siblings << sib
	}
	defer {
		for mut sib in siblings {
			sib.close()
		}
	}
	mut talker := transport.open(o.talker) or {
		eprintln('could not open talker ${o.talker}: ${err}')
		return 1
	}
	// WAIT FOR THE TALKER TO KNOW ITS OWN HEALTH before judging anything by it. Every verdict here
	// is read off the talker's fault ladder, and a backend that polls a device for it — CANsub asks
	// over HTTP from a thread started at open — has no sample yet for the first fraction of a
	// second. Phase 2 judged inside that window read "cannot say" and failed a listener that was
	// silencing perfectly. Bounded, because some backends never report and must not stall the run.
	mut warm := 0
	for warm < 3000 && talker.health() == .unknown {
		time.sleep(50 * time.millisecond)
		warm += 50
	}
	// AND LET IT RECOVER FROM THE LAST RUN. A controller's error counters decay only as frames are
	// acknowledged, so a talker that ended the previous run in a retry storm still reports warning
	// or error-passive at the start of this one — on a backend that reports its real ladder rather
	// than resetting it at open, which is what a CANsub does. Judging the baseline on that reads a
	// perfectly good bench as broken. BOUNDED BY TIME, NOT BY A FRAME COUNT: ~35 acknowledged
	// frames bring a controller from error-passive (128) below warning (96), but a backend that
	// polls a device for its health reports the change only when the next sample lands, up to a
	// second later — a 200-frame loop finished in one second and read the old sample as "still
	// degraded" (measured: the same bench passed at 126 frames and failed at 200, on timing alone).
	// Five seconds is hundreds of frames and several samples; a talker still degraded after that is.
	mut recovered := 0
	recover_until := time.ticks() + 5000
	for time.ticks() < recover_until && degraded(talker.health()) {
		talker.send(transport.CanFrame{ id: o.id, data: [u8(0x5E), u8(recovered)] }) or {}
		listener.recv(2) or {}
		time.sleep(5 * time.millisecond)
		recovered++
	}
	// DRAINED TO EMPTY, not to a count: a recovery that needed the full window left several hundred
	// frames queued, a fixed 256 took only part of them, and phase 1 then counted the rest as its
	// own — so `rx == 0`, the tool's only cable-pulled check, could never fire.
	for {
		listener.recv(1) or { break }
	}
	println('listener  ${o.listener}')
	println('talker    ${o.talker}${if talker.health() == .unknown {
		'  (reports no health; verdicts below cannot use its ladder)'
	} else if recovered > 0 {
		'  (health known after ~${warm} ms; recovered from the last run after ${recovered} acknowledged frames)'
	} else {
		'  (health known after ~${warm} ms)'
	}}')
	println('${o.frames} frames per phase, id 0x${o.id:03X}, ${o.handles} handle${if o.handles == 1 {
		''
	} else {
		's'
	}} on the listener wire')
	println('')

	mut ok := true
	// Phases a backend declines FOR A STATED DRIVER REASON. A CANsub refuses PHY reconfiguration on
	// a live channel and records a DECLARED SilenceFault the tool can read; such a phase is reported
	// as not applicable, with the device's own words, and the run still passes — a limitation the
	// code declares is not a failure of the code. A phase that fails with NO declared fault is still
	// a failure: that is the silent case this tool exists for. (Vector's mode is pinned by its ports
	// too, but its reconcile_silence records nothing yet, so on a Vector listener phase 2 FAILS
	// rather than reading n/a — stated here so nobody reads that as the tool being wrong.)
	mut not_applicable := []string{}

	// PHASE 1 — the baseline. Without it a failure in phase 2 is unreadable: a bus that was never
	// working at all produces exactly the same "talker unhealthy, listener silent" reading.
	base := exchange(mut listener, mut talker, o, true)
	println('1. baseline (listener NOT marked)')
	report(base)
	if base.rx == 0 {
		eprintln('   FAIL — nothing arrived at all. Check the cable, the termination and that both')
		eprintln('          ends are at the same bitrate; nothing below can be trusted until this passes.')
		talker.close() // a CANsub talker's threads are joined and its wire forgotten, not abandoned
		return 1
	}
	if degraded(base.talker_health) {
		eprintln('   FAIL — the talker is already unhealthy with the listener acknowledging normally.')
		talker.close()
		return 1
	}
	println('   ok — frames arrive and the talker stays ${shown(base.talker_health)}')
	println('')

	// PHASE 2 — the mark goes on WHILE BOTH ARE OPEN. Not by reopening the listener: the claim
	// being tested is that a row toggled mid-run reaches the controller, which is the case a
	// policy cached at open time gets wrong.
	transport.set_listen_only(o.listener, true)
	// RECONCILED THROUGH THE LAST SIBLING when there is one, not through the handle being read
	// from. Any handle on the wire must be able to change the mode for every one of them, and the
	// version that could not was the version where the reader happened to be the one asked.
	if siblings.len > 0 {
		siblings[siblings.len - 1].reconcile_silence(true) or {
			eprintln('   (reconcile through a sibling: ${err})')
		}
	}
	settle(mut listener, o.timeout)
	sil := exchange(mut listener, mut talker, o, true)
	println('2. listener marked listen-only, mid-run')
	report(sil)
	if !degraded(sil.talker_health) {
		if why := declined(o.listener, true) {
			println('   n/a — ${why}')
			not_applicable << 'phase 2'
		} else {
			eprintln('   FAIL — the talker is still ${shown(sil.talker_health)}. Somebody is still acknowledging')
			eprintln('          its frames, so the listener transceiver was not silenced, and no backend declared why.')
			ok = false
		}
	} else if sil.rx == 0 {
		// A listener that hears nothing is not listen-only, it is off the bus. Reported as a
		// failure of its own, because the two are easy to confuse and only one of them is correct.
		eprintln('   FAIL — the talker went ${shown(sil.talker_health)}, but the listener heard nothing.')
		eprintln('          Listen-only must still RECEIVE; this reads as the channel having left the bus.')
		ok = false
	} else {
		println('   ok — the talker went ${shown(sil.talker_health)} while the listener still heard it')
	}
	println('')

	// PHASE 3 — and off again, also mid-run. A silence that cannot be lifted without reopening is
	// half a feature, and it is the direction a "set it once at open" implementation passes phase
	// 2 and fails here.
	transport.set_listen_only(o.listener, false)
	settle(mut listener, o.timeout)
	// THE TALKER IS REOPENED, and only the talker. Phase 2 left its controller in the fault ladder
	// (bus-off transmits nothing at all), so reusing it would measure the damage rather than the
	// recovery. The listener is deliberately NOT reopened — it is the thing under test, and the
	// claim is that it changed its mind without being reopened.
	talker.close()
	mut fresh := transport.open(o.talker) or {
		eprintln('could not reopen talker ${o.talker}: ${err}')
		return 1
	}
	defer {
		fresh.close()
	}
	back := exchange(mut listener, mut fresh, o, false)
	println('3. mark cleared, mid-run')
	report(back)
	// RECOVERY IS JUDGED ON WHAT THE WIRE DOES, NOT ON THE COUNTER BEING BACK TO ZERO — and it is
	// judged FIRST. A CAN controller's transmit error counter decays by one per acknowledged
	// frame, so a CANsub talker that reached error-passive in phase 2 starts this phase there,
	// and a window judged from that state reports phase 2 again. `recover_talker` drives it back to `ok`
	// under acknowledged frames (reading the listener as it goes: mid-run, PCAN and Kvaser apply a
	// changed mark at the next receive, and the app's monitor is always receiving); a talker that
	// never gets there was never acknowledged, which is what "the silence did not lift" means.
	// `fresh`, not `talker`: phase 3 reopened the talker on purpose (see above), and the first cut
	// of this check drove the CLOSED handle — every send refused, health unknown, "never
	// recovered" for a wire that had — while the oracle (the device's own tx_error_count) showed
	// the counter falling 133 -> 0 within two seconds of the mark clearing.
	if !back.recovered {
		eprintln('   FAIL — the talker never recovered after the mark cleared: frames went out and nobody acknowledged them.')
		ok = false
	} else if severe(back.talker_health) {
		eprintln('   FAIL — the talker is still ${shown(back.talker_health)}: the silence did not lift.')
		ok = false
	} else if back.rx == 0 {
		eprintln('   FAIL — nothing arrived after clearing the mark.')
		ok = false
	} else {
		println('   ok — acknowledging again, talker back to ${shown(back.talker_health)}')
	}
	println('')

	// PHASE 4 — THE MODE OUTLIVES THE HANDLE, and this is the case that costs a bench an afternoon.
	// A run that ends while the wire is marked leaves the CONTROLLER silent; the mark itself lives
	// in this process and dies with it. So the next run opens a channel that is already silent
	// while its policy says it is not, and a backend that writes only when the policy differs from
	// its own freshly-zeroed field writes nothing and leaves it that way — a wire nobody ticked,
	// silent until somebody happens to tick and untick it.
	//
	// Reproduced here rather than described: mark, close (which is what "the last run ended" looks
	// like to the driver), clear, reopen.
	transport.set_listen_only(o.listener, true)
	settle(mut listener, o.timeout)
	// EVERY HANDLE ON THE WIRE, not just the one being read from — otherwise this phase does not
	// test what it is named after. `pcan:` opens are refcounted, so the underlying channel is only
	// uninitialized (and its mode only reset) when the LAST holder lets go; a sibling still open
	// means CAN_Uninitialize never runs and the reopen reconciles against a channel that never
	// changed. On Kvaser the siblings keep the wire alive in the same way. Closing one of three and
	// calling it "after the last handle closed" made the phase pass for a reason it does not claim
	// (codex round 6 on #219).
	listener.close()
	for mut sib in siblings {
		sib.close()
	}
	siblings.clear()
	transport.clear_listen_only()
	// AND FORGET WHAT WAS APPLIED, because that is the half a single process cannot otherwise
	// simulate. What makes this case dangerous is that the CONTROLLER remembers and the process
	// does not: `silence_applied` is empty at start-up, which is what forces the first claim on
	// every wire to write. Skip this and the table still holds "this wire is silent" from a moment
	// ago, the reopen reconciles against a record a real new run would not have, and the phase
	// passes for a reason the case it is named after does not enjoy.
	transport.forget_silence_claims()
	mut reopened := transport.open(o.listener) or {
		eprintln('could not reopen listener ${o.listener}: ${err}')
		return 1
	}
	defer {
		reopened.close()
	}
	// Reopened to the same shape as well, so the phase measures the configuration the app runs in
	// rather than a simplified one.
	for n in 1 .. o.handles {
		sib := transport.open(o.listener) or {
			eprintln('could not reopen listener handle ${n + 1}: ${err}')
			return 1
		}
		siblings << sib
	}
	fresh.close()
	mut fresh2 := transport.open(o.talker) or {
		eprintln('could not reopen talker ${o.talker}: ${err}')
		return 1
	}
	defer {
		fresh2.close()
	}
	after := exchange(mut reopened, mut fresh2, o, true)
	println('4. closed while marked, reopened unmarked')
	report(after)
	// `recovered` here is UNTAINTED: the talker was driven back to `ok` before this tool read a
	// single frame from the reopened listener, so it is the OPEN that put the controller in normal
	// mode, not a receive-side reconcile repairing it afterwards (codex round 3 on #223).
	if !after.recovered || severe(after.talker_health) || after.rx == 0 {
		eprintln('   FAIL — a channel the previous run left silent came back silent. The mark is gone')
		eprintln('          and the transceiver never heard about it.')
		ok = false
	} else {
		println('   ok — a fresh open puts the transceiver back where the policy says, not where it was left')
	}
	println('')

	// PHASE 5 — A NEW HANDLE JOINS A WIRE THIS PROCESS IS ALREADY ON, after the mark changed.
	//
	// Not an exotic case: a Lua script is explicitly allowed to outlive Stop still holding its bus,
	// so applying a project and pressing Start can open onto a wire this process never let go of —
	// and that is exactly when the policy is most likely to have just changed underneath it.
	//
	// What makes it dangerous is the measured rule from phase 2's story: canlib obeys
	// canSetBusOutputControl only through the handle holding INITIALISATION ACCESS, which the new
	// handle is not. So the mode set inside its open is ignored, silently — and an open that
	// recorded what it ASKED FOR reported the wire silenced while the controller kept acknowledging
	// (codex round 7 on #219). The mark is deliberately NOT reconciled through any existing handle
	// first: the open is the only thing that gets a chance to act on it.
	transport.set_listen_only(o.listener, true)
	println('5. mark set, then a NEW handle opened onto the already-held wire')
	if mut joiner := transport.open(o.listener) {
		joined := exchange(mut reopened, mut fresh2, o, true)
		report(joined)
		if !degraded(joined.talker_health) {
			if why := declined(o.listener, true) {
				println('   n/a — ${why}')
				not_applicable << 'phase 5'
			} else {
				eprintln('   FAIL — the talker is still ${shown(joined.talker_health)}: the joining handle did not')
				eprintln('          silence the wire, and no backend declared why.')
				ok = false
			}
		} else if joined.rx == 0 {
			eprintln('   FAIL — the talker went ${shown(joined.talker_health)}, but the listener heard nothing.')
			ok = false
		} else {
			println('   ok — opening onto a held wire reconciles it rather than assuming it was obeyed')
		}
		joiner.close()
	} else {
		// A REFUSED JOIN IS THE OTHER HONEST ANSWER. A backend that cannot silence a live channel
		// does not hand out a handle claiming to be silent (#219's rule): the join is refused with
		// the device's reason, and that reason is recorded on the wire, IN THIS DIRECTION. That is
		// the declared limitation, not a failure. Refused with no such fault, it is one. Either way
		// the run continues into the common tail below, which puts the wire back and says so if it
		// cannot -- an early return here once skipped that and printed PASS over a silent adapter.
		if why := declined(o.listener, true) {
			println('   n/a — the join was refused: ${why}')
			not_applicable << 'phase 5'
		} else {
			eprintln('   FAIL — could not open a joining handle, and no backend declared why: ${err}')
			ok = false
		}
	}
	println('')

	// AND PUT THE WIRE BACK BEFORE LEAVING. Clearing the process policy is not enough: the mode
	// belongs to the CONTROLLER and Kvaser's canClose preserves it, so a successful run ended with
	// the adapter still silent — while printing that silence does not outlive its mark. The next
	// user of that channel would have found it unable to transmit for no reason they could see
	// (codex round 8 on #219).
	//
	// Through the joining handle, which by then is just another handle on the wire; the reconcile
	// reaches all of them. Reported rather than ignored, because a bench tool that cannot hand the
	// hardware back in the state it found it should say so.
	transport.set_listen_only(o.listener, false)
	reopened.reconcile_silence(false) or {
		eprintln('WARNING: could not return ${o.listener} to normal mode — ${err}')
		eprintln('         the adapter may still be listen-only for the next thing that opens it.')
		ok = false
	}

	if ok && not_applicable.len > 0 {
		println('PASS — with ${not_applicable.join(' and ')} not applicable: this backend follows listen-only only at open, and says so on its Buses row.')
		return 0
	}
	if ok {
		println('PASS — listen-only reaches the transceiver, both directions, and does not outlive its mark.')
		return 0
	}
	println('FAIL')
	return 1
}

struct Result {
mut:
	sent          int
	send_errors   int
	rx            int
	talker_health transport.BusHealth
	// recovered: after the burst, the talker was driven to `ok` — with the listener untouched in
	// the phases that test the open. See exchange and recover_talker.
	recovered bool
}

// exchange sends one burst and drains whatever reached the listener.
//
// SEND ERRORS ARE COUNTED, NOT FATAL. In phase 2 the talker is transmitting into a bus that never
// acknowledges, so its queue backs up and the driver eventually refuses — which is a SYMPTOM of
// the thing being proved, not a failure of the tool.
// `untainted` is whether recovery must be proved WITHOUT reading the listener. Phases that test
// the OPEN (4, 5) and the mark itself (1, 2) say yes: on PCAN and Kvaser a receive re-applies the
// policy, so a read would repair the very thing under test. Phase 3 says no: it tests the mark
// changing MID-RUN, and on those backends that is applied by the next receive by design — the
// app's monitor is always reading — so a listener nobody reads never hears about it at all.
fn exchange(mut listener transport.Bus, mut talker transport.Bus, o Opts, untainted bool) Result {
	mut r := Result{}
	// SETTLED FIRST, JUDGED AFTER. The settle clears what the previous phase left in the counter
	// (a CANsub carries its real ladder across phases); its result is deliberately NOT the
	// verdict, because a talker that starts `ok` proves nothing about THIS burst — a CANsub
	// whose six frames go unacknowledged rises only to warning, a still-silent listener receives
	// the one-shot frames, and rx > 0 with warning would have passed phases 3 and 4 on a listener
	// that never acknowledged (codex round 4 on #223). So `recovered` is decided below, after the
	// burst and the untainted window, on frames driven after both.
	recover_talker(mut talker, mut listener, o, untainted)
	for i in 0 .. o.frames {
		f := transport.CanFrame{
			id:   o.id
			data: [u8(0xA5), u8(i), 0, 0, 0, 0, 0, 0]
		}
		talker.send(f) or {
			r.send_errors++
			continue
		}
		r.sent++
	}
	// THE LADDER IS SAMPLED ACROSS THE WHOLE WINDOW, not read once after the last send. A send only
	// QUEUES the frame — the controller has not attempted it yet — so a health read taken
	// immediately after the burst reports the state from before anything could go wrong. On an
	// unacknowledged bus that answer is `ok`, which is precisely the reading that makes a failure
	// of listen-only look like a pass. (Measured: phase 2 reported `ok` with zero frames arriving,
	// because the talker's frames were still sitting in its queue, unsent, for want of an ACK.)
	//
	// The WORST seen is what counts, in both directions: a controller that recovers once ACKs
	// resume would otherwise erase the evidence before the loop ends.
	// THE TALKER IS OBSERVED BEFORE THE LISTENER IS TOUCHED, and that ordering is the difference
	// between a verdict and a self-fulfilling one. Both backends reconcile the policy at the START
	// of `recv` — so a listener whose OPEN left the controller in the wrong mode gets REPAIRED by
	// the first receive, and if that receive happens before the talker's queued frames are
	// attempted, the phase passes without ever testing the open (codex round 11 on #219). Phases 4
	// and 5 are exactly the phases that claim to test the open.
	//
	// So the health of the talker — which is the whole verdict — is sampled across a window in
	// which this tool does not read from the listener at all. The frames still go out: a send
	// queued them and the controller transmits whether or not anybody is reading.
	// SHORT, because the listener is not being read during it and a silenced wire retransmits
	// continuously — a full window unread overflows the receive queue and the drain below then
	// finds nothing (measured: phase 2 went from 3300 frames to zero). Long enough is a few
	// milliseconds: a frame at 500 kbit/s is about 250 us, so 150 ms is hundreds of attempts,
	// which is all the controller needs to have failed.
	observe := time.ticks() + 150
	for time.ticks() < observe {
		time.sleep(10 * time.millisecond)
		r.talker_health = worse(r.talker_health, talker.health())
	}
	// THE VERDICT ON THIS BURST: still untainted (the listener has not been read), and required
	// to reach `ok` under frames driven now — see recover_talker for why a reading of `ok` is
	// not trusted before a second of them.
	r.recovered = recover_talker(mut talker, mut listener, o, untainted)
	// Then read normally, still sampling: a later reading can only be WORSE than the untainted one
	// above, never better, so the verdict cannot be manufactured by the reconcile in `recv`.
	deadline := time.ticks() + i64(window_ms(o))
	for time.ticks() < deadline {
		listener.recv(50) or {
			r.talker_health = worse(r.talker_health, talker.health())
			continue
		}
		r.rx++
		r.talker_health = worse(r.talker_health, talker.health())
	}
	return r
}

// recover_talker drives the talker back to `ok` before a burst is judged, and reports whether it got there.
//
// A CAN controller's transmit error counter decays by ONE per acknowledged frame, and a CANsub
// reports the real ladder (Kvaser and PCAN reset theirs on the driver's say-so): a talker that
// left the previous phase error-passive at 129 is still error-passive at the start of the next,
// whatever the listener is doing now, and a window judged from there reports the previous phase.
// The evidence that the LISTENER acknowledges is the counter coming DOWN — unacknowledged frames
// cannot do that — so frames are driven until the talker reads `ok`, five seconds at most; a
// talker still not `ok` by then was not acknowledged, which is the finding.
//
// `untainted` is whether that may happen WITHOUT reading the listener — see exchange. Judged after
// the reads instead, the recovery could be the listener's own receive-side reconcile repairing an
// open that had left it silent, and the phase would pass on the regression it exists to catch
// (codex round 3 on #223). `unknown` is a backend that cannot say, and nothing to settle.
// A READING OF `ok` IS NOT TRUSTED BEFORE A SECOND OF FRAMES. A CANsub's health is what its poll
// thread last fetched, up to ~0.6 s old, so `ok` read right after a burst can predate the burst.
// A second of frames at 5 ms is two hundred attempts: acknowledged, the counter stays at zero;
// unacknowledged, it has climbed past warning to error-passive and no stale reading survives.
// Severe is answered at once — nothing this loop sends can bring a controller nobody acknowledges
// back — and `unknown` is a backend that cannot say, which is not a failure of the wire.
fn recover_talker(mut talker transport.Bus, mut listener transport.Bus, o Opts, untainted bool) bool {
	start := time.ticks()
	until := start + 5000
	floor := start + 1000
	mut n := 0
	for time.ticks() < until {
		h := talker.health()
		if h == .unknown {
			return true
		}
		if severe(h) {
			return false
		}
		if h == .ok && time.ticks() >= floor {
			return true
		}
		talker.send(transport.CanFrame{ id: o.id, data: [u8(0x5F), u8(n)] }) or {}
		if !untainted {
			listener.recv(2) or {}
		}
		time.sleep(5 * time.millisecond)
		n++
	}
	h := talker.health()
	return h == .ok || h == .unknown
}

// window_ms — how long to watch one burst. Long enough for the controller to actually attempt
// every frame and for its counters to move, which on an unacknowledged bus takes only
// milliseconds, but the queue behind it does not empty instantly.
fn window_ms(o Opts) int {
	w := o.timeout * 3
	return if w < 600 { 600 } else { w }
}

// worse orders the fault ladder so a burst can be summarised by its worst moment. `.unknown` sorts
// below `ok` rather than above it: a backend that cannot say must never outrank one that can.
fn worse(a transport.BusHealth, b transport.BusHealth) transport.BusHealth {
	return if rank(b) > rank(a) { b } else { a }
}

fn rank(h transport.BusHealth) int {
	return match h {
		.unknown { 0 }
		.ok { 1 }
		.warning { 2 }
		.error_passive { 3 }
		.bus_off { 4 }
	}
}

// settle gives the listener one receive so its backend reconciles the mark with the controller.
//
// The reconcile happens on RECEIVE, which is what a monitored wire is doing continuously — but
// this tool is single-threaded and would otherwise change the mark and immediately transmit,
// measuring the state the controller had not been told about yet.
fn settle(mut listener transport.Bus, timeout int) {
	listener.recv(timeout) or {}
	time.sleep(50 * time.millisecond)
}

// declined reports why the listener's backend DECLINED the mode being tested — a fault on the
// wire that is in this direction AND declared to be the device's rule — or none. One rule, used by
// every phase that can be not-applicable: three hand-written copies of it disagreed in wording and
// one of them accepted any fault at all, so a driver error on PCAN or Kvaser would have read as a
// stated limitation (code-review high on #223).
fn declined(iface string, want bool) ?string {
	f := transport.wire_silence_fault(iface) or { return none }
	if f.want != want || !f.declared {
		return none
	}
	return f.why
}

// severe — the ladder rungs that mean silence did NOT lift: a talker still shut out of the bus.
fn severe(h transport.BusHealth) bool {
	return h == .error_passive || h == .bus_off
}

// degraded — anything but a controller that is happy. `.unknown` is NOT degraded: it means the
// backend cannot say, and a tool that read "cannot say" as "faulty" would report a pass in phase 2
// on any backend with no status source at all.
fn degraded(h transport.BusHealth) bool {
	return h == .warning || h == .error_passive || h == .bus_off
}

// shown — health_name answers '' for .unknown, which prints as a gap in a sentence.
fn shown(h transport.BusHealth) string {
	name := transport.health_name(h)
	return if name == '' { 'cannot say' } else { name }
}

fn report(r Result) {
	mut line := '   sent ${r.sent}/${r.sent + r.send_errors}, listener heard ${r.rx}, talker ${shown(r.talker_health)}'
	if r.send_errors > 0 {
		line += ' (${r.send_errors} refused)'
	}
	println(line)
}

fn arg_str(args []string, i int, what string) string {
	v := args[i] or {
		eprintln('${what} needs a value')
		exit(2)
	}
	return v
}

fn arg_int(args []string, i int, what string) int {
	tok := args[i] or {
		eprintln('${what} needs a value')
		exit(2)
	}
	if tok.starts_with('0x') || tok.starts_with('0X') {
		return int(tok[2..].parse_uint(16, 32) or {
			eprintln('${what}: ${tok} is not a hexadecimal number')
			exit(2)
		})
	}
	// FALLIBLE, LIKE THE HEXADECIMAL BRANCH. `.int()` answers 0 for anything it cannot read, so a
	// typo did not fail — it ran the entire hardware proof against different inputs from the ones
	// on the command line and could print PASS: `--id nope` became id 0, `--timeout nope` became a
	// zero-millisecond observation window (codex round 1 on #219). A bench tool whose result does
	// not correspond to its arguments is worse than one that refuses to start.
	return int(tok.parse_int(10, 32) or {
		eprintln('${what}: ${tok} is not a number')
		exit(2)
	})
}
