// silentcheck — prove that a wire marked listen-only stops ACKNOWLEDGING, not just transmitting.
//
// WHY THIS NEEDS A BENCH AND A SECOND NODE. Listen-only has two halves. The software half is
// `SilentBus` refusing to send, and a unit test can check it on an `inproc:` bus in microseconds.
// The hardware half cannot be checked that way at all: an ACK is generated by the CONTROLLER, on
// every frame it accepts, and the only observer of its absence is ANOTHER NODE — which sees its
// own frames fail and its error counters climb. So the measurement is necessarily two adapters and
// a cable, and the thing measured is the health of the node that is NOT under test.
//
// VENDOR-AGNOSTIC ON PURPOSE. It takes two interface strings rather than channel numbers, so the
// same run proves Kvaser against Kvaser, PCAN against PCAN, or one vendor against the other — and
// the cross-vendor pairing is the more convincing one, because neither driver is scoring its own
// homework.
//
//   v -enable-globals -path "@vlib|@vmodules|modules" run cmd/silentcheck/main.v \
//       --listener kvaser:0@500000 --talker kvaser:1@500000
//   v -enable-globals -path "@vlib|@vmodules|modules" run cmd/silentcheck/main.v \
//       --listener pcan:PCAN_USBBUS1@500000 --talker kvaser:2@500000
//
// IT TRANSMITS, from `--talker`, deliberately and repeatedly. Do not point it at a bus you are not
// willing to disturb — and note that the point of phase 2 is to drive the talker's controller into
// its fault ladder, which is a state a real ECU would report.
//
// `-enable-globals` is not optional: modules/transport/inproc.v uses `__global`.
module main

import os
import time
import transport

struct Opts {
mut:
	listener string
	talker   string
	frames   int = 6
	timeout  int = 300
	id       u32 = 0x321
	// HOW MANY HANDLES THE LISTENER WIRE HOLDS, defaulting to what a GUI Start actually opens: a
	// monitor plus transmit taps. See the `--handles` note in usage() for why this is not 1.
	handles int = 3
}

fn usage() {
	println('silentcheck — prove a listen-only wire stops acknowledging')
	println('')
	println('  --listener <iface>    the wire under test; it is marked listen-only and never sends')
	println('  --talker <iface>      the second node, on the same bus; it TRANSMITS')
	println('  --handles <n>         handles to hold open on the listener wire (default 3)')
	println('                        A GUI Start opens each wire several times — a monitor plus')
	println('                        transmit taps — and on Kvaser the channel mode CANNOT be')
	println('                        changed through one handle while its siblings are on the bus:')
	println('                        the driver accepts the call and ignores it. A one-handle bench')
	println('                        therefore passes while the real configuration silently fails,')
	println('                        which is exactly what happened. 1 to test a single handle.')
	println('  --frames <n>          frames per phase (default 6)')
	println('  --timeout <ms>        receive timeout per frame (default 300)')
	println('  --id <hex|dec>        CAN id to send (default 0x321)')
	println('')
	println('Both wires must be on one terminated bus, and they must be different wires:')
	println('a channel cannot fail to acknowledge its own transmission.')
}

fn main() {
	mut o := Opts{}
	args := os.args[1..]
	for i := 0; i < args.len; i++ {
		match args[i] {
			'--listener' {
				i++
				o.listener = arg_str(args, i, '--listener')
			}
			'--talker' {
				i++
				o.talker = arg_str(args, i, '--talker')
			}
			'--frames' {
				i++
				o.frames = arg_int(args, i, '--frames')
			}
			'--handles' {
				i++
				o.handles = arg_int(args, i, '--handles')
			}
			'--timeout' {
				i++
				o.timeout = arg_int(args, i, '--timeout')
			}
			'--id' {
				i++
				o.id = u32(arg_int(args, i, '--id'))
			}
			'--help', '-h' {
				usage()
				return
			}
			else {
				eprintln('unknown argument: ${args[i]}')
				usage()
				exit(2)
			}
		}
	}
	if o.listener == '' || o.talker == '' {
		eprintln('both --listener and --talker are required')
		usage()
		exit(2)
	}
	// THE SAME WIRE WOULD REPORT A PASS FOR THE WRONG REASON. A controller does not acknowledge
	// its own frame in the first place, so pointing both at one channel measures nothing and
	// looks like success. Compared as WIRES, so `kvaser:0@500000` and `kvaser:0` are caught.
	if transport.wire_key(o.listener) == transport.wire_key(o.talker) {
		eprintln('--listener and --talker name the same wire (${transport.wire_key(o.listener)}) — a')
		eprintln('channel never acknowledges its own transmission, so this would pass without proving anything.')
		exit(2)
	}
	if o.frames < 1 {
		eprintln('--frames must be at least 1')
		exit(2)
	}
	if o.handles < 1 {
		eprintln('--handles must be at least 1')
		exit(2)
	}
	// POSITIVE, AND THE LOWER BOUND IS NOT PEDANTRY. The Bus contract reads a NEGATIVE timeout as
	// "block forever", and `settle` receives before any traffic is sent — so `--timeout -1` did not
	// produce a wrong answer, it produced no answer at all: the tool sat in recv on a quiet bus
	// until somebody noticed (codex round 2 on #219). Zero is refused for the neighbouring reason,
	// that it makes every phase report nothing heard and phase 1 then fails the whole run for a
	// bench that is fine.
	if o.timeout < 1 {
		eprintln('--timeout must be positive (milliseconds): a negative one means "block forever" to a bus,')
		eprintln('and this tool receives before it transmits, so ${o.timeout} would hang rather than report.')
		exit(2)
	}
	exit(run(o))
}

fn run(o Opts) int {
	// CLEARED FIRST, because the table is process-wide and a stale mark from anything else in
	// this process would make phase 1's baseline a second copy of phase 2.
	transport.clear_listen_only()

	mut listener := transport.open(o.listener) or {
		eprintln('could not open listener ${o.listener}: ${err}')
		return 1
	}
	defer {
		listener.close()
	}
	// SIBLING HANDLES ON THE SAME WIRE, held open and otherwise unused, because a wire in this app
	// is normally held by several: a monitor plus named and anonymous transmit taps. They are not
	// decoration — on Kvaser the channel's output mode cannot be changed through one handle while
	// its siblings are on the bus, and the driver reports success anyway. A bench that opened the
	// listener once passed every phase while the configuration the GUI actually uses went on
	// acknowledging (codex round 5 on #219).
	mut siblings := []transport.Bus{}
	for n in 1 .. o.handles {
		sib := transport.open(o.listener) or {
			eprintln('could not open listener handle ${n + 1} of ${o.handles} on ${o.listener}: ${err}')
			return 1
		}
		siblings << sib
	}
	defer {
		for mut sib in siblings {
			sib.close()
		}
	}
	mut talker := transport.open(o.talker) or {
		eprintln('could not open talker ${o.talker}: ${err}')
		return 1
	}
	println('listener  ${o.listener}')
	println('talker    ${o.talker}')
	println('${o.frames} frames per phase, id 0x${o.id:03X}, ${o.handles} handle${if o.handles == 1 {
		''
	} else {
		's'
	}} on the listener wire')
	println('')

	mut ok := true

	// PHASE 1 — the baseline. Without it a failure in phase 2 is unreadable: a bus that was never
	// working at all produces exactly the same "talker unhealthy, listener silent" reading.
	base := exchange(mut listener, mut talker, o)
	println('1. baseline (listener NOT marked)')
	report(base)
	if base.rx == 0 {
		eprintln('   FAIL — nothing arrived at all. Check the cable, the termination and that both')
		eprintln('          ends are at the same bitrate; nothing below can be trusted until this passes.')
		return 1
	}
	if degraded(base.talker_health) {
		eprintln('   FAIL — the talker is already unhealthy with the listener acknowledging normally.')
		return 1
	}
	println('   ok — frames arrive and the talker stays ${shown(base.talker_health)}')
	println('')

	// PHASE 2 — the mark goes on WHILE BOTH ARE OPEN. Not by reopening the listener: the claim
	// being tested is that a row toggled mid-run reaches the controller, which is the case a
	// policy cached at open time gets wrong.
	transport.set_listen_only(o.listener, true)
	// RECONCILED THROUGH THE LAST SIBLING when there is one, not through the handle being read
	// from. Any handle on the wire must be able to change the mode for every one of them, and the
	// version that could not was the version where the reader happened to be the one asked.
	if siblings.len > 0 {
		siblings[siblings.len - 1].reconcile_silence(true) or {
			eprintln('   (reconcile through a sibling: ${err})')
		}
	}
	settle(mut listener, o.timeout)
	sil := exchange(mut listener, mut talker, o)
	println('2. listener marked listen-only, mid-run')
	report(sil)
	if !degraded(sil.talker_health) {
		eprintln('   FAIL — the talker is still ${shown(sil.talker_health)}. Somebody is still acknowledging')
		eprintln('          its frames, so the listener transceiver was not silenced.')
		ok = false
	} else if sil.rx == 0 {
		// A listener that hears nothing is not listen-only, it is off the bus. Reported as a
		// failure of its own, because the two are easy to confuse and only one of them is correct.
		eprintln('   FAIL — the talker went ${shown(sil.talker_health)}, but the listener heard nothing.')
		eprintln('          Listen-only must still RECEIVE; this reads as the channel having left the bus.')
		ok = false
	} else {
		println('   ok — the talker went ${shown(sil.talker_health)} while the listener still heard it')
	}
	println('')

	// PHASE 3 — and off again, also mid-run. A silence that cannot be lifted without reopening is
	// half a feature, and it is the direction a "set it once at open" implementation passes phase
	// 2 and fails here.
	transport.set_listen_only(o.listener, false)
	settle(mut listener, o.timeout)
	// THE TALKER IS REOPENED, and only the talker. Phase 2 left its controller in the fault ladder
	// (bus-off transmits nothing at all), so reusing it would measure the damage rather than the
	// recovery. The listener is deliberately NOT reopened — it is the thing under test, and the
	// claim is that it changed its mind without being reopened.
	talker.close()
	mut fresh := transport.open(o.talker) or {
		eprintln('could not reopen talker ${o.talker}: ${err}')
		return 1
	}
	defer {
		fresh.close()
	}
	back := exchange(mut listener, mut fresh, o)
	println('3. mark cleared, mid-run')
	report(back)
	if degraded(back.talker_health) {
		eprintln('   FAIL — the talker is still ${shown(back.talker_health)}: the silence did not lift.')
		ok = false
	} else if back.rx == 0 {
		eprintln('   FAIL — nothing arrived after clearing the mark.')
		ok = false
	} else {
		println('   ok — acknowledging again, talker back to ${shown(back.talker_health)}')
	}
	println('')

	// PHASE 4 — THE MODE OUTLIVES THE HANDLE, and this is the case that costs a bench an afternoon.
	// A run that ends while the wire is marked leaves the CONTROLLER silent; the mark itself lives
	// in this process and dies with it. So the next run opens a channel that is already silent
	// while its policy says it is not, and a backend that writes only when the policy differs from
	// its own freshly-zeroed field writes nothing and leaves it that way — a wire nobody ticked,
	// silent until somebody happens to tick and untick it.
	//
	// Reproduced here rather than described: mark, close (which is what "the last run ended" looks
	// like to the driver), clear, reopen.
	transport.set_listen_only(o.listener, true)
	settle(mut listener, o.timeout)
	// EVERY HANDLE ON THE WIRE, not just the one being read from — otherwise this phase does not
	// test what it is named after. `pcan:` opens are refcounted, so the underlying channel is only
	// uninitialized (and its mode only reset) when the LAST holder lets go; a sibling still open
	// means CAN_Uninitialize never runs and the reopen reconciles against a channel that never
	// changed. On Kvaser the siblings keep the wire alive in the same way. Closing one of three and
	// calling it "after the last handle closed" made the phase pass for a reason it does not claim
	// (codex round 6 on #219).
	listener.close()
	for mut sib in siblings {
		sib.close()
	}
	siblings.clear()
	transport.clear_listen_only()
	// AND FORGET WHAT WAS APPLIED, because that is the half a single process cannot otherwise
	// simulate. What makes this case dangerous is that the CONTROLLER remembers and the process
	// does not: `silence_applied` is empty at start-up, which is what forces the first claim on
	// every wire to write. Skip this and the table still holds "this wire is silent" from a moment
	// ago, the reopen reconciles against a record a real new run would not have, and the phase
	// passes for a reason the case it is named after does not enjoy.
	transport.forget_silence_claims()
	mut reopened := transport.open(o.listener) or {
		eprintln('could not reopen listener ${o.listener}: ${err}')
		return 1
	}
	defer {
		reopened.close()
	}
	// Reopened to the same shape as well, so the phase measures the configuration the app runs in
	// rather than a simplified one.
	for n in 1 .. o.handles {
		sib := transport.open(o.listener) or {
			eprintln('could not reopen listener handle ${n + 1}: ${err}')
			return 1
		}
		siblings << sib
	}
	fresh.close()
	mut fresh2 := transport.open(o.talker) or {
		eprintln('could not reopen talker ${o.talker}: ${err}')
		return 1
	}
	defer {
		fresh2.close()
	}
	after := exchange(mut reopened, mut fresh2, o)
	println('4. closed while marked, reopened unmarked')
	report(after)
	if degraded(after.talker_health) || after.rx == 0 {
		eprintln('   FAIL — a channel the previous run left silent came back silent. The mark is gone')
		eprintln('          and the transceiver never heard about it.')
		ok = false
	} else {
		println('   ok — a fresh open puts the transceiver back where the policy says, not where it was left')
	}
	println('')

	if ok {
		println('PASS — listen-only reaches the transceiver, both directions, and does not outlive its mark.')
		return 0
	}
	println('FAIL')
	return 1
}

struct Result {
mut:
	sent          int
	send_errors   int
	rx            int
	talker_health transport.BusHealth
}

// exchange sends one burst and drains whatever reached the listener.
//
// SEND ERRORS ARE COUNTED, NOT FATAL. In phase 2 the talker is transmitting into a bus that never
// acknowledges, so its queue backs up and the driver eventually refuses — which is a SYMPTOM of
// the thing being proved, not a failure of the tool.
fn exchange(mut listener transport.Bus, mut talker transport.Bus, o Opts) Result {
	mut r := Result{}
	for i in 0 .. o.frames {
		f := transport.CanFrame{
			id:   o.id
			data: [u8(0xA5), u8(i), 0, 0, 0, 0, 0, 0]
		}
		talker.send(f) or {
			r.send_errors++
			continue
		}
		r.sent++
	}
	// THE LADDER IS SAMPLED ACROSS THE WHOLE WINDOW, not read once after the last send. A send only
	// QUEUES the frame — the controller has not attempted it yet — so a health read taken
	// immediately after the burst reports the state from before anything could go wrong. On an
	// unacknowledged bus that answer is `ok`, which is precisely the reading that makes a failure
	// of listen-only look like a pass. (Measured: phase 2 reported `ok` with zero frames arriving,
	// because the talker's frames were still sitting in its queue, unsent, for want of an ACK.)
	//
	// The WORST seen is what counts, in both directions: a controller that recovers once ACKs
	// resume would otherwise erase the evidence before the loop ends.
	deadline := time.ticks() + i64(window_ms(o))
	for time.ticks() < deadline {
		listener.recv(50) or {
			r.talker_health = worse(r.talker_health, talker.health())
			continue
		}
		r.rx++
		r.talker_health = worse(r.talker_health, talker.health())
	}
	return r
}

// window_ms — how long to watch one burst. Long enough for the controller to actually attempt
// every frame and for its counters to move, which on an unacknowledged bus takes only
// milliseconds, but the queue behind it does not empty instantly.
fn window_ms(o Opts) int {
	w := o.timeout * 3
	return if w < 600 { 600 } else { w }
}

// worse orders the fault ladder so a burst can be summarised by its worst moment. `.unknown` sorts
// below `ok` rather than above it: a backend that cannot say must never outrank one that can.
fn worse(a transport.BusHealth, b transport.BusHealth) transport.BusHealth {
	return if rank(b) > rank(a) { b } else { a }
}

fn rank(h transport.BusHealth) int {
	return match h {
		.unknown { 0 }
		.ok { 1 }
		.warning { 2 }
		.error_passive { 3 }
		.bus_off { 4 }
	}
}

// settle gives the listener one receive so its backend reconciles the mark with the controller.
//
// The reconcile happens on RECEIVE, which is what a monitored wire is doing continuously — but
// this tool is single-threaded and would otherwise change the mark and immediately transmit,
// measuring the state the controller had not been told about yet.
fn settle(mut listener transport.Bus, timeout int) {
	listener.recv(timeout) or {}
	time.sleep(50 * time.millisecond)
}

// degraded — anything but a controller that is happy. `.unknown` is NOT degraded: it means the
// backend cannot say, and a tool that read "cannot say" as "faulty" would report a pass in phase 2
// on any backend with no status source at all.
fn degraded(h transport.BusHealth) bool {
	return h == .warning || h == .error_passive || h == .bus_off
}

// shown — health_name answers '' for .unknown, which prints as a gap in a sentence.
fn shown(h transport.BusHealth) string {
	name := transport.health_name(h)
	return if name == '' { 'cannot say' } else { name }
}

fn report(r Result) {
	mut line := '   sent ${r.sent}/${r.sent + r.send_errors}, listener heard ${r.rx}, talker ${shown(r.talker_health)}'
	if r.send_errors > 0 {
		line += ' (${r.send_errors} refused)'
	}
	println(line)
}

fn arg_str(args []string, i int, what string) string {
	v := args[i] or {
		eprintln('${what} needs a value')
		exit(2)
	}
	return v
}

fn arg_int(args []string, i int, what string) int {
	tok := args[i] or {
		eprintln('${what} needs a value')
		exit(2)
	}
	if tok.starts_with('0x') || tok.starts_with('0X') {
		return int(tok[2..].parse_uint(16, 32) or {
			eprintln('${what}: ${tok} is not a hexadecimal number')
			exit(2)
		})
	}
	// FALLIBLE, LIKE THE HEXADECIMAL BRANCH. `.int()` answers 0 for anything it cannot read, so a
	// typo did not fail — it ran the entire hardware proof against different inputs from the ones
	// on the command line and could print PASS: `--id nope` became id 0, `--timeout nope` became a
	// zero-millisecond observation window (codex round 1 on #219). A bench tool whose result does
	// not correspond to its arguments is worse than one that refuses to start.
	return int(tok.parse_int(10, 32) or {
		eprintln('${what}: ${tok} is not a number')
		exit(2)
	})
}
