module someip

// The golden vector below was generated by running blobly_emb's comm/e2e
// (TxState.protect on this exact payload, counter 5, data id 0x21, 9 bytes,
// ctr at 7 / crc at 8) — the port must produce bit-identical trailers or the
// GUI would reject every frame the target protects.

fn test_e2e_golden_vector_matches_emb() {
	mut data := [u8(7), 0x44, 0x33, 0x22, 0x11, 0x02, 0x01, 0x00, 0x00]
	mut tx := E2eTx{
		counter: 5
	}
	tx.protect(mut data, 0x21)
	assert data[7] == 0x05
	assert data[8] == 0x9F
	mut rx := E2eRx{}
	assert rx.check(data, 0x21) == .ok
}

fn test_e2e_rx_semantics() {
	mut tx := E2eTx{}
	mut rx := E2eRx{}
	mut a := [u8(1), 2, 3, 0, 0]
	tx.protect(mut a, 0x33)
	assert rx.check(a, 0x33) == .ok // first frame: no history, ok
	assert rx.check(a, 0x33) == .repeated // same frame again
	assert !E2eStatus.repeated.usable()
	mut b := [u8(4), 5, 6, 0, 0]
	tx.counter = (tx.counter + 2) & 0x0F // skip two frames
	tx.protect(mut b, 0x33)
	assert rx.check(b, 0x33) == .lost
	assert E2eStatus.lost.usable()
	mut c := b.clone()
	c[c.len - 1] = c[c.len - 1] ^ 0xFF // tamper the CRC
	assert rx.check(c, 0x33) == .crc_error
	// a wrong data id fails the CRC too (the id is folded into it)
	mut d := [u8(1), 2, 3, 0, 0]
	tx.protect(mut d, 0x33)
	mut rx2 := E2eRx{}
	assert rx2.check(d, 0x44) == .crc_error
	assert rx2.check([u8(1)], 0x33) == .crc_error // shorter than a trailer
}
